OPENAI_API_KEY = "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"

DB_HOST = "sql3.freesqldatabase.com"
DB_USER = "sql3816861"
DB_PASSWORD = "Xvkw87Sknd"
DB_NAME = "sql3816861"
DB_PORT = 3306
